'use strict';
/**
 * Resource file for zh g18n
 */
angular.module('ocspApp').config(['$translateProvider', function($translateProvider) {
  $translateProvider.translations('zh', {
    'ocsp_web_common_000': '流处理引擎',
    'ocsp_web_common_001': '用户名',
    'ocsp_web_common_002': '密码',
    'ocsp_web_common_003': '登录',
    'ocsp_web_common_004': '退出',
    'ocsp_web_common_005': '时',
    'ocsp_web_common_006': '分',
    'ocsp_web_common_007': '下一步',
    'ocsp_web_common_008': '上一步',
    'ocsp_web_common_009': '保存',
    'ocsp_web_common_010': '上传',
    'ocsp_web_common_011': '名字',
    'ocsp_web_common_012': '描述',
    'ocsp_web_common_013': '基础配置',
    'ocsp_web_common_014': '搜索...',
    'ocsp_web_common_015': '开',
    'ocsp_web_common_016': '关',
    'ocsp_web_common_017': '请选择',
    'ocsp_web_common_018': '名字',
    'ocsp_web_common_019': '描述',
    'ocsp_web_common_020': '取消',
    'ocsp_web_common_021': '提交',
    'ocsp_web_common_022': '提交中...',
    'ocsp_web_common_023': '秒',
    'ocsp_web_common_024': '标签',
    'ocsp_web_common_025': '事件',
    'ocsp_web_common_026': '保存成功',
    'ocsp_web_common_027': '不能为空',
    'ocsp_web_common_028': '上传成功',
    'ocsp_web_common_029': '删除成功',
    'ocsp_web_common_030': '保存失败',
    'ocsp_web_common_031': '类型',
    'ocsp_web_common_032': '表单验证失败，请检查',
    'ocsp_web_common_033': '输出配置',
    'ocsp_web_common_034': '不是有效整数',
    'ocsp_web_common_035': '字段错误',
    'ocsp_web_common_036': '无',
    'ocsp_web_common_037': '事件处理中心',
    'ocsp_web_common_038': '确定',
    'ocsp_web_common_039': '确定继续么？',
    'ocsp_web_common_040': '启用',
    'ocsp_web_common_041': '禁止',
    'ocsp_web_common_042': '编辑',

    'ocsp_web_user_manage_000':'用户管理',
    'ocsp_web_user_manage_001':'修改密码',
    'ocsp_web_user_manage_002':'当前密码',
    'ocsp_web_user_manage_003':'新密码',
    'ocsp_web_user_manage_004':'再次输入',
    'ocsp_web_user_manage_005':'密码错误，请重试',
    'ocsp_web_user_manage_006':'两次输入的密码不一致',
    'ocsp_web_user_manage_007':'用户登录过期',
    'ocsp_web_user_manage_008':'没有操作权限',
    'ocsp_web_user_manage_009':'Spark Keytab与Kafak Keytab不能相同！',
    'ocsp_web_user_manage_010':'文件不存在！',
    'ocsp_web_user_name':'用户名',
    'ocsp_web_user_desc':'用户描述',
    'ocsp_web_user_old_password':'旧密码',
    'ocsp_web_user_new_password':'新密码',
    'ocsp_web_user_new_user':'新增用户',

    'ocsp_web_system_manage_000':'系统管理',
    'ocsp_web_system_manage_001':'系统配置',
    'ocsp_web_system_manage_002':'请输入SPARK_HOME',
    'ocsp_web_system_manage_003':'新建数据源',
    'ocsp_web_system_manage_004':'新建数据源之后将无法删除，确认新建',
    'ocsp_web_system_manage_005':'请确认$OCSP_HOME/conf/OCSP_Kafka_jaas.conf配置正确以及keytab文件在$OCSP_HOME/conf中已存在',
    'ocsp_web_system_manage_006':'数据源配置',
    'ocsp_web_system_manage_007':'新建系统属性',

    'ocsp_web_label_manage_000':'标签管理',
    'ocsp_web_label_manage_001':'标签名字',
    'ocsp_web_label_manage_002':'标签实现类',
    'ocsp_web_label_manage_003':'标签参数',
    'ocsp_web_label_manage_004':'标签所有者',

    'ocsp_web_streams_manage_000':'作业流管理',
    'ocsp_web_streams_manage_001':'新建作业流',
    'ocsp_web_streams_manage_002':'作业流概要',
    'ocsp_web_streams_manage_003':'作业流配置',
    'ocsp_web_streams_manage_004':'请先选择一个作业流',
    'ocsp_web_streams_manage_005':'链接',
    'ocsp_web_streams_manage_006':'设置输入',
    'ocsp_web_streams_manage_007':'设置标签',
    'ocsp_web_streams_manage_008':'设置输出',
    'ocsp_web_streams_manage_009':'检查&提交',
    'ocsp_web_streams_manage_010':'Kafka topic',
    'ocsp_web_streams_manage_011':'输入源的字段',
    'ocsp_web_streams_manage_012':'输入源字段分隔符',
    'ocsp_web_streams_manage_013':'过滤条件',
    'ocsp_web_streams_manage_014':'作为主键的字段',
    'ocsp_web_streams_manage_015':'拖拽到这里',
    'ocsp_web_streams_manage_016':'添加输出事件',
    'ocsp_web_streams_manage_017':'事件名字',
    'ocsp_web_streams_manage_018':'需要输出的字段',
    'ocsp_web_streams_manage_019':'输出字段分隔符',
    'ocsp_web_streams_manage_020':'输出事件的时间间隔',
    'ocsp_web_streams_manage_021':'事件输出源',
    'ocsp_web_streams_manage_022':'输出到Codis中Key的前缀',
    'ocsp_web_streams_manage_023':'操作',
    'ocsp_web_streams_manage_024':'启动',
    'ocsp_web_streams_manage_025':'停止',
    'ocsp_web_streams_manage_026':'重启',
    'ocsp_web_streams_manage_027':'删除',
    'ocsp_web_streams_manage_028':'作业流运行状态',
    'ocsp_web_streams_manage_029':'作业流运行时间',
    'ocsp_web_streams_manage_030':'输出源配置',
    'ocsp_web_streams_manage_031':'输出事件',
    'ocsp_web_streams_manage_032':'已经停止',
    'ocsp_web_streams_manage_033':'正在启动',
    'ocsp_web_streams_manage_034':'正在运行',
    'ocsp_web_streams_manage_035':'正在停止',
    'ocsp_web_streams_manage_036':'正在重启',
    'ocsp_web_streams_manage_037':'事件使能',
    'ocsp_web_streams_manage_038':'输入源',
    'ocsp_web_streams_manage_039':'重试次数',
    'ocsp_web_streams_manage_040':'订阅周期',
    'ocsp_web_streams_manage_041':'选择时间段',
    'ocsp_web_streams_manage_042':'可能值',
    'ocsp_web_streams_manage_043':'开始时间必须小于结束时间',
    'ocsp_web_streams_manage_044':'正在重试',
    'ocsp_web_streams_manage_045':'添加输入源',
    'ocsp_web_streams_manage_046':'用户自定义字段',
    'ocsp_web_streams_manage_047':'可用字段',
    'ocsp_web_streams_manage_048':'生成可用字段',
    'ocsp_web_streams_manage_049':'数据流图',
    'ocsp_web_streams_manage_050':'当前用户没有配置principal和keytab',
    'ocsp_web_streams_manage_051':'启动失败',
    'ocsp_web_streams_manage_052':'作业流名称',
    'ocsp_web_streams_manage_053':'运行状态',
    'ocsp_web_streams_manage_054':'运行时间',
    'ocsp_web_streams_manage_receiveinterval':'接收间隔',
    'ocsp_web_streams_manage_exceedmaxinputsourcecount_part1':'已有',
    'ocsp_web_streams_manage_exceedmaxinputsourcecount_part2':'个输入源，不能添加新的输入源！',
    'ocsp_web_streams_case_field_name':'转义字段名',
    'ocsp_web_streams_case_expression':'case when表达式',
    'ocsp_web_streams_subscribe_type_none':'重复：无',
    'ocsp_web_streams_subscribe_type_day':'重复：每天',
    'ocsp_web_streams_subscribe_type_week':'重复：每周',
    'ocsp_web_streams_subscribe_type_month':'重复：每月',
    'ocsp_web_streams_subscribe_type_always':'重复：每批次',
    'ocsp_web_streams_chart':'指标',
    'ocsp_web_streams_owner':'作业流所有者',
    'ocsp_web_streams_from_latest':'最新的offset',
    'ocsp_web_streams_from_last_stop':'最后一次消费的offset',
    'ocsp_web_streams_cep1':'请点击  ',
    'ocsp_web_streams_cep2':'  创建事件',
    'ocsp_web_streams_cep3':'新建事件',
    'ocsp_web_streams_cep_searchfromkeyword':'通过关键字查询',
    'ocsp_web_streams_cep_addnew':'新增',
    'ocsp_web_streams_cep_classify':'分级',
    'ocsp_web_streams_cep_eventtype':'事件类型',
    'ocsp_web_streams_cep_eventtriggercondition':'事件触发条件',
    'ocsp_web_streams_cep_filedaskey':'事件主键字段',
    'ocsp_web_streams_cep_event':'事件',
    'ocsp_web_streams_cep_operation':'操作',
    'ocsp_web_streams_cep_enabled':'启用',
    'ocsp_web_streams_cep_disabled':'停用',
    'ocsp_web_streams_cep_eventlist':'事件列表',
    'ocsp_web_streams_cep_setting':'设置',
    'ocsp_web_streams_cep_eventcode':'事件编码',
    'ocsp_web_streams_cep_eventidentifier':'事件标识',
    'ocsp_web_streams_cep_eventbussinessdescription':'事件的业务含义',
    'ocsp_web_streams_cep_rule':'规则',
    'ocsp_web_streams_cep_relatedstream':'关联的流',
    'ocsp_web_streams_cep_subscribe':'订阅',
    'ocsp_web_streams_cep_submit':'提交',
    'ocsp_web_streams_cep_noteoofupdate':'版本修改说明',
    'ocsp_web_streams_cep_inputsubmissionsumary':'请输入提交纪要',
    'ocsp_web_streams_cep_search':'搜索',
    'ocsp_web_streams_cep_createclass':'新建分类',
    'ocsp_web_streams_cep_fathertype':'父分级',
    'ocsp_web_streams_cep_eventcodeexists': '事件编码已经存在！',
    'ocsp_web_streams_cep_deletetype': '删除分级',
    'ocsp_web_streams_cep_deletetypesuccess': '删除分级成功！',
    'ocsp_web_streams_cep_deletetypefailed': '删除分级失败！',
    'ocsp_web_streams_cep_cantdeletetypewithchild': '不能删除含有子分级的分级！',
    'ocsp_web_streams_cep_badgenumber': '工号',
    'ocsp_web_streams_cep_startdate': '起始时间',
    'ocsp_web_streams_cep_enddate': '结束时间',
    'ocsp_web_streams_cep_status': '状态',
    'ocsp_web_streams_cep_status_empty': '空',
    'ocsp_web_streams_cep_query': '查询',
    'ocsp_web_streams_cep_auditperiod': '订阅区间',

    'ocsp_web_common_property_zookeeper_connect': 'zookeeper的连接地址',
    'ocsp_web_common_property_zk': 'zookeeper的连接地址',
    'ocsp_web_common_property_zkpath': 'Codis的proxy在zookeeper中路径',
    'ocsp_web_common_property_metadata_broker_list': 'Broker列表',
    'ocsp_web_common_property_receiveInterval': '流数据划分批次的时间间隔',
    'ocsp_web_common_property_numExecutors': 'executor的数量',
    'ocsp_web_common_property_driverMemory': 'driver的内存',
    'ocsp_web_common_property_executorMemory': '每个executor的内存',
    'ocsp_web_common_property_queue': 'Spark streaming应用程序运行在Yarn上的队列',
    'ocsp_web_common_property_filter': '过滤条件，必须符合Spark DateFrame过滤条件表达式的格式',
    'ocsp_web_common_property_retry': '作业流异常重启次数',

    'ocsp_web_dashboard_name' : '仪表盘',
    'ocsp_web_dashboard1' : '运行状态',
    'ocsp_web_dashboard2' : '运行时长统计(分)',
    'ocsp_web_dashboard3' : '丢掉数据和处理数据量(条)',
    'ocsp_web_dashboard4' : '事件数量(个)',
    'ocsp_web_dashboard5' : '处理当前批次数据使用的时间(秒)',
    'ocsp_web_dashboard6' : '处理当前批次数据使用的存储内存(KB)',

    'ocsp_web_dashboard_memory_used': '已使用的存储内存',
    'ocsp_web_dashboard_memory_available': '可用的存储内存',

    'ocsp_web_dashboard_dropped': '丢掉数据',
    'ocsp_web_dashboard_reserved': '处理数据',
    'ocsp_web_dashboard_enabled_events': '启用事件',
    'ocsp_web_dashboard_disabled_events': '未启用事件',

    'ocsp_web_logmanagement_name': '审计日志管理',
    'ocsp_web_logmanagement_logfilename': '审计日志文件生成日期',
    'ocsp_web_logmanagement_logfileaction': '操作',
    'ocsp_web_logmanagement_checklog': '查看审计日志',
    'ocsp_web_logmanagement_checkuserdata': '查看用户数据',
    'ocsp_web_logmanagement_date': '日期',
    'ocsp_web_logmanagement_username': '用户名',
    'ocsp_web_logmanagement_usertype': '用户类型',
    'ocsp_web_logmanagement_methodtype': '方法类型',
    'ocsp_web_logmanagement_userdata': '用户数据',
    'ocsp_web_logmanagement_datadetail': '数据详情',

    'ocsp_web_common_returnback': '返回',
    'ocsp_web_common_configuration': '配置',
    'ocsp_web_common_otherconfiguration': '其他配置',

    'ocsp_web_common_propertyname': '属性名',
    'ocsp_web_common_propertyvalue': '属性值',
    'ocsp_web_events_youwillstart':'您将启动 ',
    'ocsp_web_events_youwillstop':'您将停止 ',
    'ocsp_web_events_numberofeventsstarted':' 个已经启动事件',
    'ocsp_web_events_numberofeventsstopped':' 个已经停止事件',
    'ocsp_web_events_noeventscanbestopped':' 没有事件可以被停止',
    'ocsp_web_events_noeventscanbestarted':' 没有事件可以被启动',

    'ocsp_web_common_current':'当前',
    'ocsp_web_common_statisticinfo':'统计信息',
    'ocsp_web_systemconfig_cachedatabase':'缓存数据库',

    'ocsp_web_common_property_cacheServers':'缓存服务器',
    'ocsp_web_common_property_jedisMaxIdle':'jedis最大空闲数',
    'ocsp_web_common_property_jedisMaxTotal':'jedis最大空总数',
    'ocsp_web_common_property_jedisMEM':'jedis最大内存',
    'ocsp_web_common_property_jedisMinIdle':'jedis最小空闲',
    'ocsp_web_common_property_zkSessionTimeoutMs':'ZooKeeper超时时间（毫秒）',
    'ocsp_web_common_property_jedisTimeOut':'jedis超时时间',

    'ocsp_web_common_customize':'高级',
    'ocsp_web_common_customize_property':'高级属性',
    'ocsp_web_commom_add_customize_property':'添加高级属性',
    'ocsp_web_common_other':'其它',

    'ocsp_web_alarmmanagement':'告警管理',
    'ocsp_web_alarmmanagement_config':'告警配置',
    'ocsp_web_alarmmanagement_detail':'告警详情',
    'ocsp_web_alarmmsg':'告警消息',
    'ocsp_web_common_check':'查看',
    'ocsp_web_common_showdetail':'显示详情',
    'ocsp_web_common_time':'时间',
    'ocsp_web_common_alarmtime':'告警时间',
    'ocsp_web_common_name':'名称',
    'ocsp_web_common_value':'值',

    'ocsp_web_alarm_alarmname':'告警名称',
    'ocsp_web_alarm_alarmstatus':'告警状态',
    'ocsp_web_alarm_alarmlevel':'告警级别',
    'ocsp_web_alarm_alarmcomponentname':'组件名称',

    'ocsp_web_alarm_configuration_name':'配置项名称',
    'ocsp_web_alarm_configuration_current':'当前配置',
    'ocsp_web_alarm_configuration_latest':'最新配置',
    'ocsp_web_alarm_configuration_detail':'配置详情',

    'ocsp_web_event_statistics':'事件输出统计（个） 时间：',
    'ocsp_web_event_oneevent_statistics':'事件输出统计（个）',
    'ocsp_web_allstream_statistic':'所有流的输出统计（个）',
    'ocsp_web_createstream':'创建作业流',
    'ocsp_web_common_turnback':'返回',
    'ocsp_web_stream_streamdetail':'数据流详情',
    'ocsp_web_stream_streamindex':'作业流指标',
    'ocsp_web_stream_streamconfig':'作业流配置',
    'ocsp_web_stream_configinfo':'配置信息',
    'ocsp_web_stream_basicconfig':'基础配置',
    'ocsp_web_stream_configinput':'设置输入',
    'ocsp_web_stream_configlabel':'设置标签',
    'ocsp_web_stream_configoutput':'设置输出',
    'ocsp_web_stream_checkandsubmit':'检查&提交',

    'ocsp_web_stream_pleasecheckfieldstatus':'请检查字段设置！'

  });
}]);
